CREATE TABLE IF NOT EXISTS `timeslots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day_of_week` VARCHAR(20) NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
